### ISSUE TITLE
No module named 'nadex.resources' when trying to import

### ISSUE THREAD

**Issue by aberger91** [knoguchi/nadex#1]
I was getting this error trying to use this package after installing. The reason is because in 'setup.py' you need to specify 'nadex.resources' as a package, so pip or distutils will recognize it as a submodule. Specifically line 14 in setup.py, keyword argument 'packages' to the setup function - append 'nadex.resources' to that list and you will be good to go.

**Comment by knoguchi** [comment]
Thanks.  I will fix it shortly.

I was using setuptools with the `find_packages()` until recently.   I still like setuptools but I thought I'd try out the Python3 standard stuff.

**Comment by knoguchi** [comment]
Python2.7 appeared to have the reported problem while Python3.5, and 3.6 are ok.   Please try with Python3.5 or later.   Python2 support is not considered as I'm using async/await syntax.

**Comment by knoguchi** [comment]
Fixed in the master.  Thanks!

**Comment by knoguchi** [comment]
By the way, I decided to switch back to setuptools.
