### ISSUE TITLE
name 'connection' is not defined

### ISSUE THREAD

**Issue by aberger91** [knoguchi/nadex#2]
In nadex/rest_api.py, there is the import 'from nadex.connection import *', but then in the constructor for NadexRestAPI, there is syntax 'connection.Connection', which is unnecessary and should be changed to just 'Connection'

**Comment by knoguchi** [comment]
The import * is for the resources, not the connection.  The connection is imported by `from nadex import connection`.

**Comment by knoguchi** [comment]
Closing this ticket.
